[General]
network = scenario12345
sim-time-limit = 3000s
debug-on-errors = true
cmdenv-express-mode = true
image-path = ../../../../images

# ==============================================================
# 1) CONFIGURADOR DE LA RED FIJA + RUTA MANUAL PARA node[0]
# ==============================================================
*.configurator.addStaticRoutes = true
*.configurator.addDefaultRoutes = true
*.configurator.optimizeRoutes = true
*.configurator.assignAddresses = true
*.configurator.assignDisjunctSubnetAddresses = true
*.configurator.displayAddresses = true
*.configurator.dumpAddresses = true
*.configurator.dumpRoutes = true
*.configurator.dumpLinks = true
*.configurator.dumpTopology = true
*.configurator.dumpConfig = "startupDump.xml"
**.routingTable.netmaskRoutes = ""
**.configurator.addSubnetRoutes = true
**.configurator.addDefaultRoutes = true
**.configurator.config = xmldoc("rutas.xml")
*.server.numWlanInterfaces = 0
# ==============================================================
# 2) FORWARDING EN NODOS INTERMEDIOS
# ==============================================================
#*.rsu[*].ipv4.ip.forwarding = true
*.router.ipv4.ip.forwarding = true
#*.rsu[*].forwarding = true
# GlobalArp ayuda a resolver MAC rápidamente en la simulación
**.ipv4.arp.typename = "GlobalArp"
**.ipv4.arp.globalArp = true

# ==============================================================
# 3) AUTOCONFIGURACIÓN DE LOS AUTOS (OBLIGATORIA EN TU ENFOQUE)
# ==============================================================
# Ojo: HostAutoConfigurator solo pone IP/máscara. No pone rutas.
# Por eso arriba le metimos la ruta default a node[0].
*.node[*].ipv4.configurator.typename = "HostAutoConfigurator"
*.node[*].ipv4.configurator.interfaces = "wlan0 lo0"
*.node[*].ipv4.configurator.addressBase = "10.0.0.50"
*.node[*].ipv4.configurator.netmask = "255.255.0.0"
*.node[*].ipv4.routingTable.routingFile = "rutas_autos.mrt"
#*.node[1].ipv4.configurator.typename = "HostAutoConfigurator"
#*.node[1].ipv4.configurator.interfaces = "wlan0 lo0"
#*.node[1].ipv4.configurator.addressBase = "10.0.0.50"
#*.node[1].ipv4.configurator.netmask = "255.255.0.0"
#*.node[1].ipv4.configurator.netmask = "255.255.0.0"

# ==============================================================
# 5) CONFIGURACIÓN RADIO E INFRAESTRUCTURA (AP)
# ==============================================================
*.**.wlan[*].radio.antenna.typename = "IsotropicAntenna"
*.node[*].wlan[0].radio.displayCommunicationRange = true

# Usamos *.rsu*. para aplicar a rsu1, rsu2, etc.
*.rsu*.wlan[0].radio.displayCommunicationRange = true
*.radioMedium.obstacleLoss.typename = "IdealObstacleLoss"
**.wlan[*].radio.radioMediumModule = "radioMedium"

# --- COMANDO DE POTENCIA DE TRANSMISIÓN ---
*.**.wlan[*].radio.transmitter.power = 1mW 

# --- MODO INFRAESTRUCTURA ---
*.rsu*.wlan[*].mgmt.ssid = "VANET"
*.node[*].wlan[*].mgmt.typename = "Ieee80211MgmtSta"
*.node[*].wlan[*].agent.typename = "Ieee80211AgentSta"
*.node[*].wlan[*].agent.defaultSsid = "VANET"
*.node[*].wlan[*].agent.activeScan = true
# ==============================================================
# 6) MOVILIDAD / VEINS
# ==============================================================
*.playgroundSizeX = 20000m
*.playgroundSizeY = 20000m
*.playgroundSizeZ = 50m
*.node[*].mobility.typename = "VeinsInetMobility"
*.rsu*.mobility.typename = "StationaryMobility"

# --- Posición RSU 1 (Coincide con p=534.969, 26.6 del .ned) ---
*.rsu1.mobility.initialX = 534.969m
*.rsu1.mobility.initialY = 26.6m
*.rsu1.mobility.initialZ = 0m

# --- Posición RSU 2 (Coincide con p=1034.98, 26.6 del .ned) ---
*.rsu2.mobility.initialX = 1034.98m 
*.rsu2.mobility.initialY = 26.6m
*.rsu2.mobility.initialZ = 0m

*.rsu3.mobility.initialX = 1423.4m 
*.rsu3.mobility.initialY = 334.999m
*.rsu3.mobility.initialZ = 0m

*.rsu4.mobility.initialX = 315m 
*.rsu4.mobility.initialY = 523.4m
*.rsu4.mobility.initialZ = 0m

*.node[*].wlan[*].radio.antenna.mobilityModule = "^.^.^.mobility"
*.rsu[*].wlan[*].radio.antenna.mobilityModule = "^.^.^.mobility"
*.veinsManager.host = "localhost"
*.veinsManager.port = 9999
*.veinsManager.updateInterval = 0.1s
*.veinsManager.autoShutdown = true
*.veinsManager.launchConfig = xmldoc("wifirec.launchd.xml")
*.veinsManager.moduleName = "node"
*.veinsManager.moduleType = "org.car2x.veins.subprojects.veins_inet.VeinsInetCar"

# ==============================================================
# 7) MEDIO / VISUALIZACIÓN
# ==============================================================
*.visualizer.interfaceTableVisualizer.displayInterfaceTables = true
*.visualizer.routingTableVisualizer.displayRoutingTables = true
*.visualizer.routingTableVisualizer.destinationFilter = "*"
*.visualizer.physicalLinkVisualizer.displayLinks = true
*.visualizer.dataLinkVisualizer.displayLinks = true
*.visualizer.networkRouteVisualizer.displayRoutes = true

**.vector-recording = true

[configPing]
# ==============================================================
# 4) APLICACIONES (PingApp)
# ==============================================================
# Limpiamos las aplicaciones por defecto
#*.node[*].numApps = 0
#*.rsu[*].numApps = 0
#*.router.numApps = 0

# El servidor no necesita aplicación para responder pings (ICMP lo hace solo)
*.server.numApps = 0

# --- Auto 0 ---
*.node[0].numApps = 1
*.node[0].app[0].typename = "PingApp"
*.node[0].app[0].destAddr = "server"
*.node[0].app[0].printPing = true
*.node[0].app[0].startTime = 5s

# --- Auto 1 ---
*.node[1].numApps = 1
*.node[1].app[0].typename = "PingApp"
*.node[1].app[0].destAddr = "server"
*.node[1].app[0].printPing = true
*.node[1].app[0].startTime = 5.2s


[configFileTransfer]
# 1. EL SERVIDOR (Receptor del Archivo)
# Usaremos TcpSinkApp, que simplemente absorbe toda la data que le llegue
*.server.numApps = 1
*.server.app[0].typename = "TcpSinkApp"
*.server.app[0].localPort = 1000

# 2. LOS AUTOS (Emisores del Archivo)
# --- Auto 0 ---
*.node[0].numApps = 1
*.node[0].app[0].typename = "TcpSessionApp"
*.node[0].app[0].connectAddress = "server"
*.node[0].app[0].connectPort = 1000
*.node[0].app[0].tOpen = 5.5s        # Hora en que inicia la conexión (SYN)
*.node[0].app[0].tSend = 5.6s        # Hora en que empieza a enviar el archivo
*.node[0].app[0].sendBytes = 1GiB     # Tamaño del archivo a enviar
*.node[0].app[0].tClose = 0s         # 0s significa "no cerrar hasta terminar de enviar"

# --- Auto 1 ---
*.node[1].numApps = 1
*.node[1].app[0].typename = "TcpSessionApp"
*.node[1].app[0].connectAddress = "server"
*.node[1].app[0].connectPort = 1000
*.node[1].app[0].tOpen = 5.8s
*.node[1].app[0].tSend = 5.9s
*.node[1].app[0].sendBytes = 1GiB
*.node[1].app[0].tClose = 0s


[Config Telemetry]
description = "Transmisión de telemetría TCP basada en paradas de SUMO"

# ==============================================================
# 1. EL SERVIDOR (Receptor de Telemetría)
# ==============================================================
*.server.numApps = 1
*.server.app[0].typename = "wifitelemetry.TelemetryTcpFinal.TelemetryReceiverTcpFinal"

*.server.app[0].localPort = 1000

# ==============================================================
# 2. LOS AUTOS (Emisores de Telemetría)
# ==============================================================
# Aplicamos a todos los nodos (buses) usando *.node[*]
*.node[*].numApps = 1
*.node[*].app[0].typename = "wifitelemetry.TelemetryTcpFinal.TelemetrySenderTcpFinal"

# Configuración de Red
*.node[*].app[0].connectAddress = "server"
*.node[*].app[0].connectPort = 1000

# Temporizadores (Manteniendo la precisión que configuraste en tu C++)
*.node[*].app[0].startTime = 5s
*.node[*].app[0].sampleInterval = 1s
*.node[*].app[0].batchInterval = 5s
*.node[*].app[0].helloInterval = 0.5s
*.node[*].app[0].conditionCheckInterval = 0.1s

# --- MAPEO DE PARADAS (Lógica de transmisión reactiva) ---
# routeStops: El orden lógico de la ruta para los logs
*.node[*].app[0].routeStops = "bs_0, bs_1, bs_2, bs_3, bs_4, bs_5"

# validStops: LAS PARADAS AUTORIZADAS PARA TRANSMITIR
# Si el bus se detiene en CUALQUIERA de estas paradas y tiene WiFi, transmitirá.
*.node[*].app[0].validStops = "bs_0, bs_1, bs_2, bs_3, bs_4, bs_5"
